# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
schedules:
- cron: "* * * * *"
  displayName: Hourly build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: 'src/AzureWebMonitor.Test.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: 'src/AzureWebMonitor.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: 'src/AzureWebMonitor.Test.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
